In [1]:
import pandas as pd
df = pd.read_csv('../data/raw/superstore.csv', encoding='latin1')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,Hon Deluxe Fabric Upholstered Stacking Chairs,731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680,2,0.20,2.5164

In [2]:
df.info()
df.describe()
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         5 non-null      int64
 1   Order ID       5 non-null      str
 2   Order Date     5 non-null      str
 3   Ship Date      5 non-null      str
 4   Ship Mode      5 non-null      str
 5   Customer ID    5 non-null      str
 6   Customer Name  5 non-null      str
 7   Segment        5 non-null      str
 8   Country        5 non-null      str
 9   City           5 non-null      str
 10  State          5 non-null      str
 11  Postal Code    5 non-null      int64
 12  Region         5 non-null      str
 13  Product ID     5 non-null      str
 14  Category       5 non-null      str
 15  Sub-Category   5 non-null      str
 16  Product Name   5 non-null      str
 17  Sales          5 non-null      float64
 18  Quantity       5 non-null      int64
 19  Discount       5 non-null      float64
 20  Profit         5 non-null      float64
dtypes: float64(3), int64(3), str(15)
memory usage: 1.8 KB

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='str')

In [3]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [4]:
df.columns = df.columns.str.strip()
df = df.drop_duplicates()

df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

df['Revenue'] = df['Sales']
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Revenue
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,261.9600
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,Hon Deluxe Fabric Upholstered Stacking Chairs,731.9400,3,0.00,219.5820,731.9400
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels,14.6200,2,0.00,6.8714,14.6200
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,957.5775
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold N Roll Cart System,22.3680,2,0.20,2.5164,22.3680

In [5]:
orders = df[['Order ID','Order Date','Ship Date','Customer ID','Product ID','Region','Revenue']]
customers = df[['Customer ID','Customer Name','Segment','Region']].drop_duplicates()
products = df[['Product ID','Category','Sub-Category','Product Name']].drop_duplicates()
regions = df[['Region','State','City']].drop_duplicates()

orders.head()

,Order ID,Order Date,Ship Date,Customer ID,Product ID,Region,Revenue
0,CA-2016-152156,2016-11-08,2016-11-11,CG-12520,FUR-BO-10001798,South,261.9600
1,CA-2016-152156,2016-11-08,2016-11-11,CG-12520,FUR-CH-10000454,South,731.9400
2,CA-2016-138688,2016-06-12,2016-06-16,DV-13045,OFF-LA-10000240,West,14.6200
3,US-2015-108966,2015-10-11,2015-10-18,SO-20335,FUR-TA-10000577,South,957.5775
4,US-2015-108966,2015-10-11,2015-10-18,SO-20335,OFF-ST-10000760,South,22.3680

Data cleaned and standardized
Revenue column created
Tables split for normalization
Ready for ETL pipeline